// Generic AI provider abstraction. Every agent calls through this interface,
// never a vendor SDK directly, so swapping OpenAI <-> Anthropic <-> Gemini
// <-> a local model later is a one-file change (see the provider map at the
// bottom) rather than a rewrite of agent logic.

export interface TextGenParams {
  system?: string;
  prompt: string;
  maxTokens?: number;
}

export interface ImageGenParams {
  prompt: string;
  referenceImageUrls?: string[]; // for character/style consistency
}

export interface AudioGenParams {
  text: string;
  voice?: string;
}

export interface VideoGenParams {
  prompt: string;
  referenceImageUrl?: string;
  durationSeconds?: number;
}

export interface AIProvider {
  name: string;
  generateText(params: TextGenParams): Promise<string>;
  generateImage(params: ImageGenParams): Promise<{ url: string }>;
  generateAudio(params: AudioGenParams): Promise<{ url: string }>;
  generateVideo(params: VideoGenParams): Promise<{ url: string }>;
}

// --- Demo provider -----------------------------------------------------
// Produces deterministic, readable mock output instantly, so the whole
// office/orchestration/animation system is testable with zero API keys.
// This is what runs whenever DEMO MODE is on.
class DemoProvider implements AIProvider {
  name = "demo";

  private async settle<T>(value: T, ms = 0): Promise<T> {
    if (ms) await new Promise((r) => setTimeout(r, ms));
    return value;
  }

  async generateText({ prompt }: TextGenParams): Promise<string> {
    return this.settle(
      `[Demo output for prompt: "${prompt.slice(0, 60)}${
        prompt.length > 60 ? "…" : ""
      }"]\n\nThis is placeholder text generated by Demo Mode so the workflow can be tested without an API key. Connect a real provider in lib/ai/provider.ts to replace this with generated content.`
    );
  }

  async generateImage(_: ImageGenParams): Promise<{ url: string }> {
    return this.settle({ url: "/demo-assets/placeholder-image.svg" });
  }

  async generateAudio(_: AudioGenParams): Promise<{ url: string }> {
    return this.settle({ url: "/demo-assets/placeholder-audio.txt" });
  }

  async generateVideo(_: VideoGenParams): Promise<{ url: string }> {
    return this.settle({ url: "/demo-assets/placeholder-video.txt" });
  }
}

// --- Real providers --------------------------------------------------------
// Every agent runs in the browser (see lib/orchestrator/orchestrator.ts,
// triggered straight from TaskInputPanel), so these classes never call a
// vendor API directly — that would ship OPENAI_API_KEY / ANTHROPIC_API_KEY /
// GEMINI_API_KEY to every visitor's browser. Instead they call this app's
// own server routes (app/api/ai/text, app/api/ai/image, app/api/ai/audio),
// which hold the real keys server-side. Add your keys to .env.local (see
// .env.example), set NEXT_PUBLIC_AI_PROVIDER, and turn Demo Mode off — no
// other code changes needed.

async function postJSON<T>(url: string, body: unknown): Promise<T> {
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const data = await res.json();
  if (!res.ok) {
    throw new Error(data?.error || `Request to ${url} failed (${res.status})`);
  }
  return data as T;
}

class OpenAIProvider implements AIProvider {
  name = "openai";
  async generateText({ system, prompt, maxTokens }: TextGenParams): Promise<string> {
    const { text } = await postJSON<{ text: string }>("/api/ai/text", {
      provider: "openai",
      system,
      prompt,
      maxTokens,
    });
    return text;
  }
  async generateImage({ prompt }: ImageGenParams): Promise<{ url: string }> {
    return postJSON<{ url: string }>("/api/ai/image", { provider: "openai", prompt });
  }
  async generateAudio({ text, voice }: AudioGenParams): Promise<{ url: string }> {
    return postJSON<{ url: string }>("/api/ai/audio", { provider: "openai", text, voice });
  }
  async generateVideo(): Promise<{ url: string }> {
    throw new Error(
      "No video provider is configured yet. OpenAI doesn't currently offer one — pair with a dedicated video-generation service (e.g. Runway, Pika, Luma) behind its own /api/ai/video route, same pattern as /api/ai/text."
    );
  }
}

class AnthropicProvider implements AIProvider {
  name = "anthropic";
  async generateText({ system, prompt, maxTokens }: TextGenParams): Promise<string> {
    const { text } = await postJSON<{ text: string }>("/api/ai/text", {
      provider: "anthropic",
      system,
      prompt,
      maxTokens,
    });
    return text;
  }
  async generateImage(): Promise<{ url: string }> {
    throw new Error("Anthropic does not generate images — pair with an image provider (e.g. set NEXT_PUBLIC_AI_PROVIDER=openai for Pixel's department, or add one to app/api/ai/image/route.ts).");
  }
  async generateAudio(): Promise<{ url: string }> {
    throw new Error("Anthropic does not generate audio — pair with a voice provider (e.g. ElevenLabs) behind a new /api/ai/audio route.");
  }
  async generateVideo(): Promise<{ url: string }> {
    throw new Error("Anthropic does not generate video — pair with a video provider behind a new /api/ai/video route.");
  }
}

class GeminiProvider implements AIProvider {
  name = "gemini";
  async generateText({ system, prompt, maxTokens }: TextGenParams): Promise<string> {
    const { text } = await postJSON<{ text: string }>("/api/ai/text", {
      provider: "gemini",
      system,
      prompt,
      maxTokens,
    });
    return text;
  }
  async generateImage(): Promise<{ url: string }> {
    throw new Error(
      "Gemini image generation (Imagen) needs a Vertex AI setup this app doesn't wire up yet — pair with OpenAI's image route, or add a Vertex-backed case to app/api/ai/image/route.ts."
    );
  }
  async generateAudio(): Promise<{ url: string }> {
    throw new Error("No audio provider is configured yet — add one behind a new /api/ai/audio route.");
  }
  async generateVideo(): Promise<{ url: string }> {
    throw new Error(
      "Gemini/Veo video generation needs a Vertex AI setup this app doesn't wire up yet — add a case to a new /api/ai/video route."
    );
  }
}

const providers: Record<string, AIProvider> = {
  demo: new DemoProvider(),
  openai: new OpenAIProvider(),
  anthropic: new AnthropicProvider(),
  gemini: new GeminiProvider(),
};

// Single entry point the rest of the app uses. Reads NEXT_PUBLIC_DEMO_MODE
// and NEXT_PUBLIC_AI_PROVIDER from the environment by default; the office
// UI's Demo Mode toggle passes an explicit override so switching it live in
// the browser doesn't require a rebuild.
//
// This is deliberately NEXT_PUBLIC_AI_PROVIDER, not AI_PROVIDER: every agent
// (and therefore this function) runs client-side, and Next.js only inlines
// NEXT_PUBLIC_* vars into the browser bundle — a plain AI_PROVIDER would
// silently read as undefined here. That's fine to expose; it's just a
// provider name ("openai"/"anthropic"/"gemini"), not a secret. The actual
// API keys stay server-only, read only inside app/api/ai/*/route.ts.
export function resolveProvider(forceDemo?: boolean): AIProvider {
  const envDemo = process.env.NEXT_PUBLIC_DEMO_MODE !== "false";
  const demoMode = forceDemo ?? envDemo;
  if (demoMode) return providers.demo;
  const providerName = process.env.NEXT_PUBLIC_AI_PROVIDER || "demo";
  return providers[providerName] ?? providers.demo;
}
